language: node_js
node_js:
- '10'
cache:
  yarn: true
  directories:
  - "./node_modules"
sudo: required
before_install:
- sudo apt-key adv --fetch-keys http://dl.yarnpkg.com/debian/pubkey.gpg
- echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
- sudo apt-get update -qq
- sudo apt-get install -y -qq yarn=1.5.1-1
addons:
  chrome: stable
install:
- yarn install
before_script:
- yarn global add @vue/cli
- yarn global add firebase-tools
script:
- yarn run lint
- yarn run build
deploy:
  skip_cleanup: true
  provider: firebase
  token:
    secure: Qkw035iSuIj5pME9i2jkgSUnleD7OTs6Y5LwKzNJKNdOJ+PghAhphpIwa/Hy0l+2sjL6/ZJMTx0DQ+dwWSUsYrwSE62iRXYK48gNErui/tHIGpJmceVegfWhpwWbIlfI03T8kj6zKR2t/w5rTF7h9yL6Bc2g32XNo2N7fN6pUjfBSo0ET6uUJ2PalGyqrRcVryfzBEnu8CghVNaxkHpvzxl/6od/hkZLstJUh6QnI0JFaNUW2kSAMzMKHX/RWJGOPXwgZxXRYIFW2aOPEIEc911EnZElaEgKiDB7CPwDPL/H9ONj0plckYQnhpb2N4z202ICdnghWPAVPtaZV5NoDaI3V05st/XmcIl39i3OphPEoSQZzcV1cPaqc84S/CIdDzpxdNkzlSx+0Ccb/ySroC6VWqjTfEHfnoEVXfcyEJUm7iV4HgWjywszF/Hb9pU0U1Y9oGQKwe2HSxDNIH+KUDKxpk+RESk4ZdiiXI9o+zjR3Dm93TGUTMtTsK5npVHZLupbeukjiwG2op8dxs2sWI/dDlt6jyu2GSIYnqy3Xx6FtTenT1dkS5XrvEmSehIAFCfoYCUQ+f21qMNZc6PtaKZv1IlcF2xNdBIop1Bryb6Wc9aGhQFXL+BVXYZktWhJMM2ixAFU0106ERGbas2n1FwVdZHYNmtNf3hC9+qBnLA=
notifications:
  email: false

